FROM python:3.8-slim

WORKDIR /bentoml

COPY requirements.txt .
COPY bentofile.yaml .
COPY setup.py .
COPY commands.sh .

RUN apt-get update && apt-get upgrade -y && apt-get install -y git && pip install -r requirements.txt

COPY ./data ./data
COPY ./src ./src
EXPOSE 3000

ENTRYPOINT ["bash", "commands.sh"]